--- 
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка проксирующего nginx
  hosts: vm_2 # Будет работать на машине vm_2
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Установка и настройка веб-сервера nginx 
  hosts: vm_3 # Будет работать на машине vm_3
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom
