
---
# tasks file for nginx_custom

- name: Установка Nginx на машину vm_3
  apt:
    update_cache: yes
    name: "nginx"
    state: present
  when: "'vm_3' in inventory_hostname" # установка nginx на машину vm_3

- name: Подмена веб-страницы на машине vm_3
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'vm_3' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_3
  notify: "Nginx Reloader"

- name: Меняем имя машины - способ 1.
  shell: "echo 'vm4' > /etc/hostname"
  when: (inventory_hostname != ansible_hostname) and ('vm_3' in inventory_hostname)

- name: Меняем имя машины - способ 2.
  ansible.builtin.hostname:
    name: "vm4"

